# Configuration file for the drone detection project

paths:
  raw_data_dir: 'data/raw'  # Path to raw images
  processed_data_dir: 'data/processed_data'  # Path to store processed data
  model_save_dir: 'saved_models'  # Directory to save the trained model

image:
  width: 224  # Image width for resizing
  height: 224  # Image height for resizing
  channels: 1  # 1 for grayscale, 3 for RGB

train:
  batch_size: 32  # Batch size for training
  epochs: 30  # Number of epochs to train

model:
  cnn_filters: 32  # Number of filters in CNN layers
  cnn_kernel_size: [3, 3]  # Kernel size for CNN layers
  lstm_units: 64  # Number of units in LSTM layer
  dense_units: 128  # Number of units in dense layer
  num_classes: 15  # Total number of classes (drone types * scenarios)

